### ISSUE TITLE
apt-key  를 gpg 로 ..

### ISSUE THREAD

**Issue by ngenieer** [hyunwoongko/python-mecab-kor#3]
인스톨하다가 timeout 으로 안넘어가길래  봤는데 아래 부분이었어요.

/scripts/install_requirements.sh  25번째 라인입니다. 

**sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC**

그래서 이걸 아래와 같이 바꾸었더니 문제없이 잘 돌아갔습니다.

**sudo gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys A4B469963BF863CC**

언제부터인지는 모르겠는데  apt-key 는 depricated  라고 하네요. 
아무런 방화벽 없는 시스템에서는 apt-key  도 잘 작동했습니다.

감사합니다. 덕분에 잘 사용하고 있습니다.

**Comment by hyunwoongko** [comment]
에러가 발생한 OS 정보를 알려주시겠어요?

**Comment by hyunwoongko** [comment]
v1.2.4에서 해결되었습니다.
